server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJFdmVyeW9uZSIsIlVzZXJuYW1lIjoiRXZlcmJvZHkifQ
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"